---
title: "Exploratory Analysis - Emissions"
author: "Andrew Deighan"
date: "June 27, 2017"
output: html_document
---

```{r}
home <- getwd()
```

```{r}
library(xlsx)
library(dplyr)

maine_CO2emiss <- read.xlsx("data/CO2 Emissions - Maine.xlsx", sheetIndex = 1, header = TRUE)

head(maine_CO2emiss)
```


  Creat a tidy data set and save as csv file

```{r}
library(dplyr)

years <- 1980:2014
sectors <- c(as.character(unique(maine_CO2emiss[4:29,1])[!is.na(unique(maine_CO2emiss[4:29,1]))]), "All")
sources <- c("Coal", "Petroleum Products", "Natural Gas", "All")

maine_CO2tidy <- data.frame(year = rep(years, each = 24),
                            sector = rep(rep(sectors, each = 4), length(years)),
                            source = rep(sources, 6*length(years)),
                            carbdiox_millmtrcton = rep(NA, 24*length(years)))

r <- c(5:8,11:14,17:20,23:26,29:32,37:40)
c <- 3:37

maine_CO2tidy <- maine_CO2tidy %>% mutate(carbdiox_millmtrcton = as.vector(as.numeric(as.matrix(maine_CO2emiss[r,c]))))

write.csv(maine_CO2tidy, "data/CO2 Emissions - tidyMain.csv", row.names = FALSE)
```

  Plot

```{r}
plot(x = maine_CO2tidy$year[maine_CO2tidy$sector == "All" & maine_CO2tidy$source == "All"],
     y = maine_CO2tidy$carbdiox_millmtrcton[maine_CO2tidy$sector == "All" & maine_CO2tidy$source == "All"],
     type = "l", xlab = "Year", ylab = expression(paste(CO[2], " Emissions (millions of metric tons)")))
```






